### ISSUE TITLE
Reliability of TTS output.

### ISSUE THREAD

**Issue by TBTHEDBA** [jekalmin/extended_openai_conversation#104]
Using the same prompt I can get output to TTS about 1/4 of the time. Should I create a function for TTS functionality to get more reliable results? The particular prompt I am trying it "Using tts.cloud_say send my work events to media_player.basement_speaker."

**Comment by TBTHEDBA** [comment]
That did the trick. Tied it in with your image query to give descriptions of rooms.

**Comment by danielp370** [comment]
I thought I'd document here - this is a more generic example. The LLM knows your devices so has no problems with this function:
```
- spec:
    name: say_tts
    description: Say message on a text to speech device
    parameters:
      type: object
      properties:
        message:
          type: string
          description: message you want to say
        device:
          type: string
          description: entity_id of media_player tts device
      required:
      - message
      - device
  function:
    type: script
    sequence:
    - service: tts.cloud_say
      data:
        entity_id: "{{device}}"
        message: "{{message}}"
```
