### ISSUE TITLE
Incorrect example in the documentation

### ISSUE THREAD

**Issue by RadzuPL** [jekalmin/extended_openai_conversation#126]
In the documentation at:
https://github.com/jekalmin/extended_openai_conversation/blob/main/examples/function/weather/README.md#function
The get_attributes function is pasted instead of weather function.

**Comment by jekalmin** [comment]
Thanks for reporting an issue!

This was intended that asking weather can be achieved using `get_attributes` function.
However, as you said, it seems like typo. I will fix README.

**Comment by TBTHEDBA** [comment]
What weather services do you use? I am getting false returns from both weather.openweathermap and weather.pirateweather

**Comment by jekalmin** [comment]
Although I'm using [naver_weather](https://github.com/miumida/naver_weather) which is designed to support Korea only, `weather` entity should have the same format, I guess, like below.

<img width="600" alt="스크린샷 2024-02-01 오전 11 32 55" src="https://github.com/jekalmin/extended_openai_conversation/assets/2917984/90139268-6866-4dd2-a20c-896402595413">

Have you exposed `weather.xxx` entity?

**Comment by TBTHEDBA** [comment]
It is exposed and says that it is referencing the correct Enitity when I ask where it derived it's data from. But it keeps giving 25F (-4C) as the forecasted temperature for any request (Example: What will the temp be at 7am tomorrow / What will the coldest day be next week?) when the temps are more in the 60F (15C) range.

**Comment by TBTHEDBA** [comment]
Update: 
I think I found the issue. I had both the original function for weather and get attribute. Once I removed the original function, I am getting correct results.

**Comment by TBTHEDBA** [comment]
Further update:  That wasn't the issue the symptom has returned. 

-----
Assist: How can I assist?

Me: What will the temp be at 8am tomorrow?

Assist:I'm unable to provide the weather forecast for tomorrow at 8 am without access to an external weather service. If you have a weather sensor integrated into your smart home system, I can retrieve the current temperature for you.

Me: why didn't you use weather.openweathermap?

Assist: My apologies for the oversight. The forecasted temperature for tomorrow at 8 am is approximately 62.73°F based on the OpenWeatherMap integration in your smart home system.

------

It is giving me the current weather. Sometimes it will look at the forecast and other times return current temp as forecasted temp.

**Comment by TBTHEDBA** [comment]
I can get proper returns from my chatgpt 4 customGPT 
![image](https://github.com/jekalmin/extended_openai_conversation/assets/40796990/8310510f-45f1-43c3-9aff-44c4bfe46118)

**Comment by jekalmin** [comment]
When asked about forecast, it seems gpt doesn't call `get_attribute` function of weather entity.
In my case, it calls [get_events](https://github.com/jekalmin/extended_openai_conversation/tree/main/examples/function/calendar#1-get_events) function instead.

I think this is because gpt calls date or time relevent functions if exist rather than calls `get_attribute` of weather entity.
If I ask `How is the weather?` and then ask about forecast seems working for me.

**Comment by Scags104** [comment]
use this as a function. Seems to work for me where there are updated weather services to the new HA spec where service call to get_forecasts is needed:

`- spec:
    name: get_weather_forecast
    description: get weather forecast
    parameters:
      type: object
      properties:
        type:
          type: string
          description: the type of forecast
          enum:
            - daily
            - hourly
      required:
      - type
  function:
    type: script
    sequence:
    - service: weather.get_forecasts
      data:
        type: "{{type}}"
      target:
        entity_id: weather.pirate_weather
      response_variable: _function_result`

**Comment by Scags104** [comment]
hopefully the above works now with formatting. sorry about that. any tips on how to format in one code block is appreciated

**Comment by TBTHEDBA** [comment]
I think if you have it copied with the formatting (say from your notepad++) then it keeps that formatting if you select code block.

**Comment by Scags104** [comment]
that didnt work but i did figure it out. 3 ticks on each end

````
```
test
   code
```
````

**Comment by Scags104** [comment]
good to hear!

@jekalmin can we add this to the weather example? being lazy and dont want to PR so you can take all the credit :)

**Comment by Scags104** [comment]
@TBTHEDBA can you test something?
Ask it "what is the weather in 3 hours"

when i do it i get a WILD token error:
`Sorry, I had a problem talking to OpenAI: Error code: 400 - {'error': {'message': "This model's maximum context length is 16385 tokens. However, your messages resulted in 23954 tokens (23269 in the messages, 685 in the functions). Please reduce the length of the messages or functions.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}`

**Comment by TBTHEDBA** [comment]
Same response as you.

**Comment by Scags104** [comment]
@jekalmin can you comment on what the issue may be given the function posted above and the token error?

Thanks

**Comment by TBTHEDBA** [comment]
I switched the model to gpt-4-0125-preview and got the proper response back.

**Comment by Scags104** [comment]
tried that model but get a different error now: 

`Sorry, I had a problem talking to OpenAI: Error code: 429 - {'error': {'message': 'Request too large for gpt-4-turbo-preview in organization org-SAwImXKORCENZ8CcLdMW3snF on tokens per min (TPM): Limit 10000, Requested 15657. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}`

**Comment by jekalmin** [comment]
Thanks @Scags104 for your help!

I wasn't aware that `weather.get_forecasts` service exists.
I just installed and tried pirate weather, and it's returning hourly data from now to a week later, which is huge (about 19,000 tokens)

service call | [tokens](https://platform.openai.com/tokenizer)
--|--
<img width="1481" alt="스크린샷 2024-02-16 오후 11 39 51" src="https://github.com/jekalmin/extended_openai_conversation/assets/2917984/1967e811-5a36-4d7a-9974-2e2cdaa67ebc"> | <img width="796" alt="스크린샷 2024-02-16 오후 11 34 36" src="https://github.com/jekalmin/extended_openai_conversation/assets/2917984/c8cd6d10-caa4-47d2-9523-44ec8f54e9a2">

Since we need only one row of data, we have to narrow all hourly data into one to reduce token size.

```yaml
- spec:
    name: get_weather_forecast
    description: get weather forecast
    parameters:
      type: object
      properties:
        datetime:
          type: string
          description: The date time like "2024-02-16T14:00:00+00:00".
        type:
          type: string
          description: the type of forecast
          enum:
            - daily
            - hourly
      required:
      - type
  function:
    type: composite
    sequence:
      - type: script
        sequence:
          - service: weather.get_forecasts
            data:
              type: "{{type}}"
            target:
              entity_id: weather.pirateweather
            response_variable: _function_result
        response_variable: result
      - type: template
        value_template: "{{result['weather.pirateweather'].forecast | selectattr('datetime', 'contains', datetime) | list}}"
```

It should be something like above.

1. Get datetime that we are interested.
2. Compare it with datetime of forecasts to find weather at specific time.

Although it works with hourly forecast, it doesn't work with daily forecast in my case.
The daily forecast is returning `15:00:00` rather than `00:00:00`. (I'm located in +9 hours zone)
I'm still concerning how to resolve this issue.

<img width="800" alt="1" src="https://github.com/jekalmin/extended_openai_conversation/assets/2917984/617d8f84-50c8-4ad5-9f7c-f695ec925844">

**Comment by jekalmin** [comment]
This is what I currently have.
Please try this out.

<img width="300" src="https://github.com/jekalmin/extended_openai_conversation/assets/2917984/acbc7988-43b0-4c8b-82c4-6bc544087b7b">


```yaml
- spec:
    name: get_weather_forecast
    description: get weather forecast
    parameters:
      type: object
      properties:
        datetime:
          type: string
          description: The date time like "2024-02-16T14:00:00+00:00".
        type:
          type: string
          description: the type of forecast
          enum:
            - daily
            - hourly
      required:
      - type
  function:
    type: composite
    sequence:
      - type: script
        sequence:
          - service: weather.get_forecasts
            data:
              type: "{{type}}"
            target:
              entity_id: weather.pirateweather
            response_variable: _function_result
        response_variable: result
      - type: template
        value_template: >-
          {%- set forecasts = result['weather.pirateweather'].forecast | selectattr('datetime', 'contains', as_timestamp(datetime) | timestamp_custom('%Y-%m-%dT%H:00:00+00:00', false, 'UTC')) | list %}
          {%- for forecast in forecasts %}
          {{ dict(forecast, datetime=forecast.datetime | as_timestamp | timestamp_custom('%Y-%m-%dT%H:%M:%S')) }}
          {%- endfor %}
```
