### ISSUE TITLE
can't use to activate automations

### ISSUE THREAD

**Issue by starschild86** [jekalmin/extended_openai_conversation#129]
hi!
i'm trying to create a new automation to get my little one involved into this home assistant adventure :slight_smile: 
she has a doll and she always asks me "how cute is sorellina?" (the name of her dolly) and i reply her with a number from 1 to 5.
i would like to have home assistant to be able to do the same thing leveraging an automation but i'm running into some problems.

i've created an automation like the one below - see yaml below for reference - however it seems that it prioritizes looking the web rather than being the input of the automation and it does reply something along the lines of "i cannot reply this question accurately as i don't have specific information on you or your family" (i translated because i run home assistant and chatgpt in italian)

am i missing something?

thanks a lot,
Nicola

```
alias: piccolezza sorellina
description: ""
trigger:
  - platform: conversation
    command: Quanto è piccola sorellina
condition: []
action:
  - service: tts.speak
    metadata: {}
    data:
      cache: true
      media_player_entity_id: media_player.vlc_telnet
      message: 5
mode: single
```

**Comment by TBTHEDBA** [comment]
```
- spec:
    name: say_tts_family_room
    description: Say message
    parameters:
      type: object
      properties:
        message:
          type: string
          description: message you want to say on family room wifi.
      required:
      - message
  function:
    type: script
    sequence:
    - service: tts.cloud_say
      data:
        entity_id: media_player.family_room_wifi
        message: "{{message}}"
```

This is the spec I had to create to get TTS functionality into extended.

**Comment by starschild86** [comment]
Thanks! So I guess I will add something like this in the functions section of the integration configuration, do you say something particular to the voice assistant in order to trigger this action instead of other things?
Can the speaker be the same as the one you are talking to?

**Comment by TBTHEDBA** [comment]
```
service: conversation.process
data:
  agent_id: e817a5bfac9040401e94c5ff9471fc11
  text: Say how cute sorellina is on basement display
```

Sorry I don't have satellite speakers so I can't test that for you but you can hard code a speaker in (doesn't have to be the speaker mentioned in the spec.
