### ISSUE TITLE
Example of a POST request as a function

### ISSUE THREAD

**Issue by s1061429** [jekalmin/extended_openai_conversation#134]
Thanks for this great project! I am trying to do a POST request as a function, but can you provide an example of how to do this? Thanks!

**Comment by jekalmin** [comment]
For `rest` type,  schema is same as [REST](https://www.home-assistant.io/integrations/rest/) in Home Assistant.
The difference is that `value_template` is added in this integration, so that you can modify API result.

**Form data**

```yaml
- spec:
    name: get_your_data
    description: Get your data
    parameters:
      type: object
      properties:
        dummy:
          type: string
          description: Nothing.
  function:
    type: rest
    method: POST
    resource: "https://YOUR_POST_API"
    payload: "foo=foo&bar=bar"
    headers:
      "Content-Type": "application/x-www-form-urlencoded; charset=utf-8"
    value_template: '{{value_json}}'
```

**JSON**

```yaml
- spec:
    name: get_your_data
    description: Get your data
    parameters:
      type: object
      properties:
        dummy:
          type: string
          description: Nothing.
  function:
    type: rest
    method: POST
    resource: "https://YOUR_POST_API"
    payload: >-
      {"foo": "foo", "bar": "bar"}
    headers:
      "Content-Type": "application/json; charset=utf-8"
    value_template: '{{value_json}}'
```
