### ISSUE TITLE
Small fix for youtube on WebOs (LG) 

### ISSUE THREAD

**Issue by gterras** [jekalmin/extended_openai_conversation#139]
Hi there, 

It seems that playing a specific youtube video on a LG TV now needs a `v=` prefix in `contentId`: 

```
    - service: webostv.command
      data:
        entity_id: media_player.{YOUR_WEBOSTV}
        command: system.launcher/launch
        payload:
          id: youtube.leanback.v4
          contentId: "v={{video_id}}" 
```

Without it it just leads to the youtube home page.
