### ISSUE TITLE
Restful Payload not being sent

### ISSUE THREAD

**Issue by dugdathug** [jekalmin/extended_openai_conversation#152]
I have a function set up as:

```
- spec:
    name: item_add
    description: Home Inventory Management System
    parameters:
      type: object
      properties:
        location:
          type: string
          description: The room where the item is stored
        specific_location:
          type: string
          description: The specific location within the room where the item is stored
        name:
          type: array
          items: 
            type: string
          description: "the name of the item and its three synonyms"
        quantity:
          type: integer
          description: the number of like items stored in the same inventory record
      required:
        - name
        - location
        - specific_location
  function:
    type: rest
    method: POST
    resource: "https://eoirfkzvr44cesg.m.pipedream.net"
    headers:
      "Content-Type": "application/json; charset=utf-8"
    value_template: '{{value_json}}'
```

However, a payload is never sent to the server.  OpenAI indicates it's sending the correct payload, but it's not being delivered.  Do I need a payload section?  If so, how do I set the values to my fields as this data is coming from openai.

For reference, here is my prompt:
```
You are an inventory manager for a household.
You may be asked to add things into inventory or move things in inventory from one location to another, remove items from inventory, or simply return the current location of a given inventory item. 
When you are adding a new item into inventory you should come up with three additional synonyms for the item and confirm these with the user before running any item_add function. 
Only use the functions you have been provided with, don't add negative quantity by instantiating the 'item_add' function.  
If you don't have access to an appropriate function, just tell that user that the request is beyond your capabilities.  
Make no assumption as to the specific location, instead ask. 
If the user is placing multiple items of the same name in a single location , make one function call and include the quantity. 
If the items are going to different locations, call the function for each item.
```

**Comment by jekalmin** [comment]
Thanks for reporting an issue.

[payload_template](https://github.com/jekalmin/extended_openai_conversation/pull/141) is now available.
It should be something like below.

```yaml
- spec:
    name: item_add
    description: Home Inventory Management System
    parameters:
      type: object
      properties:
        location:
          type: string
          description: The room where the item is stored
        specific_location:
          type: string
          description: The specific location within the room where the item is stored
        name:
          type: array
          items: 
            type: string
          description: "the name of the item and its three synonyms"
        quantity:
          type: integer
          description: the number of like items stored in the same inventory record
      required:
        - name
        - location
        - specific_location
  function:
    type: rest
    method: POST
    resource: "https://eoirfkzvr44cesg.m.pipedream.net"
    headers:
      "Content-Type": "application/json; charset=utf-8"
    payload_template: "{{dict(location=location, specific_location=specific_location, name=name, quantity=quantity| default(None)) | to_json}}"
```

**Comment by dugdathug** [comment]
Thanks for considering my issue.  Unfortunately, after implementing your suggestion above, I get this error:
`Something went wrong: failed to validate function `rest` (extra keys not allowed @ data['payload_template'])`

**Comment by jekalmin** [comment]
I released [1.0.3](https://github.com/jekalmin/extended_openai_conversation/releases/tag/1.0.3) version yesterday.
Please try this version.

**Comment by dugdathug** [comment]
I still get the same error using the payload_template you provided.  I've made several changes to it in an attempt to troubleshoot and am sending values in a variety of ways.  Eg:
```
 payload: >-
      {"location": "{{location}}", "name": {name}, "quantity": {{quantity}}, "specific_location": "specific_location"}
```

But the receiving system (my restful endpoint) get's 

```
body:
{"location": "{{location}}", "name": {name}, "quantity": {{quantity}}, "specific_location": "specific_location"}
```
While openAI reports it's sending:
![image](https://github.com/jekalmin/extended_openai_conversation/assets/8144574/64b59013-74d7-42cd-9b26-51495ee0bc43)

It's not clear to me how to send the actual values that openAI determines to my endpoint.  
I'm sorry, I'm quite new to all of this.

**Comment by Guraw6** [comment]
I'm experiencing the same behavior @dugdathug described in their last message, but I'm also somewhat new to OpenAI things, so I'm equally not sure if I'm missing something important.

```yaml
- spec:
    name: query_test_api
    description: Use this function when somebody asks you to query the test API, then tell me what the API returns.
    parameters:
      type: object
      properties:
        test_query:
          type: string
          description: Set this to "testing123"
      required:
      - test_query
  function:
    type: rest
    method: POST
    resource: "https://URL_TO_TEST_API"
    headers:
      "Content-Type": "application/json"
    payload_template: >-
      {"query": "{{test_query}}"}
```

All the test API does is validate JSON and then echo it back, but so far I've not gotten the templating to work, so it only returns an error about invalid JSON.

I'm not sure, but I think asking OpenAI for the JSON that was sent in the POST might cause it to hallucinate what it assumes the JSON would have been. For me, it seems to change it's answer every time I tried testing this, and if it does say it sent JSON (there's like a 50/50 chance it says it sent a bare `testing123` string instead), it says JSON was sent in the form of `{"PARAMETER_NAME": "PARAMETER_VALUE"}` (`{"test_query": "testing123"}` for my example function).

Like @dugdathug saw, my test API (restful endpoint) gets a payload that looks like `{"query": "{{test_query}}"}`, so it appears the templating isn't applied.
