### ISSUE TITLE
History function exceeds context length

### ISSUE THREAD

**Issue by mgc8** [jekalmin/extended_openai_conversation#157]
First of all, thanks for this awesome integration, it turns HA into an _actual_ Assistant!

I am using a few custom functions to add more functionality, among them the `get_history` one defined [here](https://github.com/jekalmin/extended_openai_conversation/tree/main/examples/function/history).

The function works well, but in some instances (e.g. if I ask about a sensor with a very long history), it returns so many results that it overflows the context length and I get an error from the API (which is fortunate, otherwise the costs form that many tokens could quickly add up!). It would be good to have a way to limit the size of the `ns.result` returned to a specified maximum (e.g. 2046/4096/etc.), truncating the results to the most recent historical values up to that point. That would solve the issue nicely, while avoiding overflows or extreme costs from the API.

**Comment by jekalmin** [comment]
Thanks for reporting an issue.

Maybe we can apply paging, but I'm quite not sure if gpt can respond that there are more data.
I added `last` property to tell gpt that there are more data, but it seems not satisfactory.

```yaml
- spec:
    name: get_history
    description: Retrieve historical data of specified entities.
    parameters:
      type: object
      properties:
        entity_ids:
          type: array
          items:
            type: string
            description: The entity id to filter.
        start_time:
          type: string
          description: Start of the history period in "%Y-%m-%dT%H:%M:%S%z".
        end_time:
          type: string
          description: End of the history period in "%Y-%m-%dT%H:%M:%S%z".
        page:
          type: integer
          description: The page number
        page_size:
          type: integer
          description: The page size defaults to 10
      required:
      - entity_ids
      - page
      - page_size
  function:
    type: composite
    sequence:
      - type: native
        name: get_history
        response_variable: history_result
      - type: template
        value_template: >-
          {%- set ns = namespace(result = [], list = [], last = True) %}
          {%- for item_list in history_result %}
              {%- set ns.list = [] %}
              {%- for item in item_list %}
                  {% if (page-1) * page_size < loop.index and loop.index <= page * page_size %}
                    {%- set last_changed = item.last_changed | as_timestamp | timestamp_local if item.last_changed else None %}
                    {%- set new_item = dict(item, last_changed=last_changed) %}
                    {%- set ns.list = ns.list + [new_item] %}
                  {% endif %}
              {%- endfor %}
              {%- set ns.result = ns.result + [ns.list] %}
              {{ns.list | length}}
              {%- if ns.last == True and ns.list | length == page_size %}
                {%- set ns.last = False %}
              {%- endif %}
          {%- endfor %}
          {{ dict(result=ns.result,last=ns.last) }}
```
