### ISSUE TITLE
Help building spotcast function

### ISSUE THREAD

**Issue by Xornop** [jekalmin/extended_openai_conversation#169]
when i add any
- spec
Line to the functions field, the LLM is not responding and just says the error 
Something went wrong: failed to load functions. Verify functions are valid in a yaml format
I am adding a function from your examples and that even gives the error, making me think its not my own code.

**Comment by jekalmin** [comment]
Thanks for reporting an issue.
Could you share a full yaml of functions?

**Comment by Xornop** [comment]
I realised now that I just didn't have the corresponding integrations installed for the functions i tried to add. This was late at night trying to make my own function for the spotcast add on. So I guess I need help with making a function for that. I changed the issue title accordingly.
Can you spot my mistake?
Maybe you can add some guidance in the docs on how to make a function?

`- spec:
    name: play_spotify
    description: Play Spotify on a device
    parameters:
      type: object
      properties:
        device:
          type: string
          description: The device on which to play Spotify
  function:
    type: script
    sequence:
      - service: spotcast.start
          data:
            force_playback: true
            random_song: true
            repeat: context
            shuffle: true
            offset: 0
            ignore_fully_played: false
            account: user1
            device_name: DESKTOP
`

**Comment by sajov** [comment]
@Xornop i also try to integrate a function for spotcast, Can you share details of yours?

**Comment by Xornop** [comment]
```
- spec:
    name: play_spotify
    description: Play Spotify on a device
  function:
    type: script
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: media_player.spotify_user1
                state: paused
            sequence:
              - service: spotcast.start
                data:
                  force_playback: true
                  random_song: true
                  repeat: context
                  shuffle: true
                  offset: 0
                  ignore_fully_played: false
                  account: user1
                  device_name: DESKJOP
          - conditions:
              - condition: state
                entity_id: media_player.spotify_user1
                state: playing
            sequence:
              - service: media_player.media_pause
                target:
                  entity_id: media_player.spotify_user1
                data: {}
```
@sajov
