### ISSUE TITLE
Trigger automation with voice

### ISSUE THREAD

**Issue by pjuhl2313** [jekalmin/extended_openai_conversation#170]
I was wondering if it is possible to trigger an automation with using Extended Open AI as your conversation agent?

**Comment by jekalmin** [comment]
Which one do you mean?

1. automation trigger → conversation agent
2. conversation agent → automation

If what you asked is the first one, you can achieve it by `conversation.process` service.

**Comment by pjuhl2313** [comment]
> Which one do you mean?
> 
>     1. automation trigger → conversation agent
> 
>     2. conversation agent → automation
> 
> 
> If what you asked is the first one, you can achieve it by `conversation.process` service.

I'm trying to get the second one to work.

**Comment by jekalmin** [comment]
You can use `script` function to change state of entities or trigger events like below.

```yaml
- spec:
    name: trigger_event
    description: trigger event
    parameters:
      type: object
      properties:
        dummy:
          type: string
          description: Nothing
  function:
    type: script
    sequence:
      - event: "your_event_name"
        event_data: {}
```

You can modify name and description of spec, and event of function to fit your case.
Then add event trigger to your automation.
