### ISSUE TITLE
Can VoiceAsisstant lern?

### ISSUE THREAD

**Issue by WW1983** [jekalmin/extended_openai_conversation#191]
I don't know much about ChatGPT or programming. Therefore the question may seem stupid:

If GPT doesn't understand a command and I explain it differently, it saves it as a context. But only as long as the chat window is open. Is there a way to insert a command like "learn this" without anything similar and GPT saves it in the prompt?

**Comment by Andrerm124** [comment]
In theory you could have a text helper entity which you expose to ChatGPT and tell it to use the contents as part of its prompt, and then in the prompt say something like “When I ask you to remember XYZ update the Prompt entity”

**Comment by jleinenbach** [comment]
I created a todo list and told ChatGPT to take notes. This works very well vor ChatGPT 4, but not really for ChatGPT 3.5

**Comment by WW1983** [comment]
not a bad idea with the to-do list. But I think this can easily be solved on the program side, such a context memory

**Comment by WW1983** [comment]
> I created a todo list and told ChatGPT to take notes. This works very well vor ChatGPT 4, but not really for ChatGPT 3.5

what doesn't work with ChatGPT 3.5?

**Comment by jleinenbach** [comment]
ChatGPT 3.5 tends to irrelevant notes like: "optimze the search" while ChatGPT 4 actually writes down HOW it can do that after a discussion. There's ChatGPT 5 in a few months, so I hope we can get rid of ChatGPT 3.5.

**Comment by WW1983** [comment]
> ChatGPT 3.5 neigt zu irrelevanten Notizen wie: „Suche optimieren“, während ChatGPT 4 nach einer Diskussion tatsächlich aufschreibt, WIE es das tun kann. In ein paar Monaten gibt es ChatGPT 5, also hoffe ich, dass wir ChatGPT 3.5 loswerden können.

I can do notes with GPT 3.5 though. But I can't get a link so that when I execute a command, I also look at the to-do list. Do you have a solution for that?

**Comment by jleinenbach** [comment]
What do you mean? Do you want to get the to-do list items?

```
- spec:
    name: get_items_from_list
    description: >-
      Retrieves items from a specified list, with an optional filter for their status. Suitable for lists identified by entity IDs starting with `todo.`, reflecting various needs.
    parameters:
      type: object
      properties:
        list:
          type: string
          description: The entity ID of the list to retrieve items from, prefixed with `todo.`.
        status:
          type: string
          description: (Optional) Set to a predefined value to filter items by their current state.
          optional: true
      required:
        - list
  function:
    type: script
    sequence:
      - service: todo.get_items
        data:
          status: "{{ status | default('needs_action') }}"
        target:
          entity_id: "{{ list }}"
        response_variable: _function_result
```
