### ISSUE TITLE
Something went wrong service sensor.read not found

### ISSUE THREAD

**Issue by pop-vapor** [jekalmin/extended_openai_conversation#215]
I am trying to read data from the entity sensor.test_feed

Which has entries that look like this:

```
- title: News title
  link: https://somelink.com/story
- title: Another title
  link: https://www.nytimes.com/2024/05/13/nyregion/mercer-county-threats-white-people.html
```
  
  I ensured that the entity is exposed to the voice assistant, but with the extended_openai_conversation agent selected if I ask "please read me one title from the test feed" it returns:
  
 "Something went wrong: Service sensor.read not found"
 
 It's able to access other entities like my zigbee lights, so not sure what the problem is here.

**Comment by raicerocks** [comment]
For any that have this issue in the future, Iwas able to fix by adding the following to functions:

```
- spec:
    name: get_attributes
    description: Get attributes of any home assistant entity
    parameters:
      type: object
      properties:
        entity_id:
          type: string
          description: entity_id
      required:
      - entity_id
  function:
    type: template
    value_template: "{{states[entity_id]}}"
```
