### ISSUE TITLE
get_attributes function only pulls current day from weather.forecast_home

### ISSUE THREAD

**Issue by pop-vapor** [jekalmin/extended_openai_conversation#218]
My get_attributes function:
```
## Get Entity Attributes
- spec:
    name: get_attributes
    description: Get attributes of any home assistant entity
    parameters:
      type: object
      properties:
        entity_id:
          type: string
          description: entity_id
      required:
      - entity_id
  function:
    type: template
    value_template: "{{states[entity_id]}}"
```

If I ask the assistant to get me the weather for today, it usually works. If I ask it for tomorrow's forecast in the same conversation, it's unable to comply:
![image](https://github.com/jekalmin/extended_openai_conversation/assets/61396754/a8406c56-9813-4a23-9d58-7254bdb5ccbf)

If I start a conversation asking for tomorrow's weather, it'll give me todays:
![image](https://github.com/jekalmin/extended_openai_conversation/assets/61396754/a4da12e5-3495-48ed-badc-e8afea4aaae5)

I originally thought that the issue was the assistant calling `weather.get_forecast` instead of `weather.get_forecasts`, but since I read bug reports for similar issues being fixed with the attribute search function, I'm wondering if my issue is similar.

Thanks!

**Comment by pop-vapor** [comment]
This was solved here https://github.com/jekalmin/extended_openai_conversation/issues/126#issuecomment-1946826733

The creator of this function discussed having issues with using it to grab hourly data from pirateweather, but it works perfectly with the default entity weather.forecast_home.
```
## Get Weather
- spec:
    name: get_weather_forecast
    description: get weather forecast
    parameters:
      type: object
      properties:
        type:
          type: string
          description: the type of forecast
          enum:
            - daily
            - hourly
      required:
      - type
  function:
    type: script
    sequence:
    - service: weather.get_forecasts
      data:
        type: "{{type}}"
      target:
        entity_id: weather.forecast_home
      response_variable: _function_result
```

![image](https://github.com/jekalmin/extended_openai_conversation/assets/61396754/c323e0a9-9da2-49a7-a17b-6c36e1cbc867)
![image](https://github.com/jekalmin/extended_openai_conversation/assets/61396754/2a627657-6a5f-44a5-8a5a-32735e658cec)
