### ISSUE TITLE
Use Google Maps to navigate on smartphone [Feature Request]

### ISSUE THREAD

**Issue by pbuergi** [jekalmin/extended_openai_conversation#229]
open Google Maps Navigation on smartphone:

```
- spec:
    name: navigate_to_location
    description: Starts navigation to a specified location via Google Maps on your phone.
    parameters:
      type: object
      properties:
        location:
          type: string
          description: The location to navigate to (e.g. address or place name)
      required:
      - location
  function:
    type: script
    sequence:
      - service: notify.mobile_app_<device id>
        data:
          message: "command_activity"
          data:
            intent_package_name: "com.google.android.apps.maps"
            intent_action: "android.intent.action.VIEW"
            intent_uri: "google.navigation:q={{ location }}"
```
