### ISSUE TITLE
Add multiple items to shoping list

### ISSUE THREAD

**Issue by AndrewSpec** [jekalmin/extended_openai_conversation#282]
Currently I can add one item at a time.

It'll be nice to add a list of items. Why? Because you can ask ChatGPT for a list of items for dinner and add the whole list to shopping list. Curently it's working only with the first item.

**Comment by mateuszstalmach** [comment]
I also had this problem and wrote something like this:
`- spec:
    name: add_items_to_shopping_list
    description: Funkcja pozwala na dodawanie wieluelementów do listy zakupów
    parameters:
      type: object
      properties:
        items:
          type: array
          items:
            type: string
          description: Lista elementów do dodania do listy zakupów
      required:
      - items
  function:
    type: script
    sequence:
    - repeat:
        for_each: "{{ items }}"
        sequence:
        - service: shopping_list.add_item
          data:
            name: "{{ repeat.item }}"`

**Comment by AndrewSpec** [comment]
> I also had this problem and wrote something like this: `- spec: name: add_items_to_shopping_list description: Funkcja pozwala na dodawanie wieluelementów do listy zakupów parameters: type: object properties: items: type: array items: type: string description: Lista elementów do dodania do listy zakupów required: - items function: type: script sequence: - repeat: for_each: "{{ items }}" sequence: - service: shopping_list.add_item data: name: "{{ repeat.item }}"`

Without proper yaml formatting it's hard to get it right.

**Comment by jekalmin** [comment]
Thanks for sharing a function!
Feel free to contribute in [example](https://github.com/jekalmin/extended_openai_conversation/tree/develop/examples/function/shopping_list)

```
- spec:
    name: add_items_to_shopping_list
    description: Funkcja pozwala na dodawanie wieluelementów do listy zakupów
    parameters:
      type: object
      properties:
        items:
          type: array
          items:
            type: string
            description: Lista elementów do dodania do listy zakupów
      required:
        - items
  function:
    type: script
    sequence:
      - repeat:
          for_each: "{{ items }}"
          sequence:
            - service: shopping_list.add_item
              data:
                name: "{{ repeat.item }}"
```
