### ISSUE TITLE
Need help with func-definition

### ISSUE THREAD

**Issue by spamferkel** [jekalmin/extended_openai_conversation#287]
Maybe someone can give me hint what i am doing wrong here. I'm trying to get  a weather-forecast with the blueprint from https://github.com/TheFes/ha-blueprints/blob/main/weather/3_voice_weather_forecast_full_llm.yaml to work. But my spec seems to have an issue. ExtendedOpenAIConversation says "Something went wrong: failed to load functions. Verify functions are valid in a yaml format". Here's my spec:

```
- spec:
    name: get_weather_forecast
    description: Get weather forecast
    parameters:
      type: object
      properties:
        time_period_type:
          type: string
          description: >-
          This argument is mandatory and must always be provided no matter what! Use 'daily' in case the request is for full days, examples: today, next Thursday, coming weekend. Use 'hourly' in case the request is for a part of a day, examples: at 8 hours this evening, next morning, this evening, from 3 to 5
        time_period_length:
          type: number
          description: >-
          This argument is mandatory and must always be provided no matter what! The length of the time period. This will be the number of days in case the 'time_period_type' is 'daily' and the number of hours in case 'time_period_type' is 'hourly'. Examples: 1 (day) if the request is for the forecast of today, 2 (days) if the request is for the weather this weekend, 6 (hours) if the request is for the weather periods like night, morning, afternoon and evening
        start_date:
          type: string
          description: >-
          This argument is mandatory and must always be provided no matter what! Provide the date on which the requested forecast starts. This date should be in the format YYYY-MM-DD. Always provide a date, so in case request is the forecast for today, provide today's date. When the forecast is for the night, do not use today's dat but always use the next day, unless the current time is still before 05:00:00
        start_time:
          type: string
          description: >-
          This argument is mandatory and must always be provided no matter what! Provide the time on which the requested forecast starts. This time should be in the format HH:MM:SS in 24 hour format (for example 17:00:00). Always provide a time. In case a full day is requested, use 00:00:00, in case the current hour is requested, use the start of the hour. Night starts at 00:00:00, morning starts at 06:00:00, afternoon starts at 12:00:00 and evening starts at 18:00:00
      required:
      - time_period_type
      - time_period_length
      - start_date
      - start_time
  function:
    type: script
    sequence:
    - service: script.llm_weather_forecast
      data:
        time_period_type: {{time_period_type}}
        start_date: {{start_date}}
        start_time: {{start_time}}
        time_period_length: {{time_period_length}}
```

**Comment by jekalmin** [comment]
Try this.

- indentation after next line of description.
- wrap template variable with `"`

```yaml
- spec:
    name: get_weather_forecast
    description: Get weather forecast
    parameters:
      type: object
      properties:
        time_period_type:
          type: string
          description: >-
            This argument is mandatory and must always be provided no matter what! Use 'daily' in case the request is for full days, examples: today, next Thursday, coming weekend. Use 'hourly' in case the request is for a part of a day, examples: at 8 hours this evening, next morning, this evening, from 3 to 5
        time_period_length:
          type: number
          description: >-
            This argument is mandatory and must always be provided no matter what! The length of the time period. This will be the number of days in case the 'time_period_type' is 'daily' and the number of hours in case 'time_period_type' is 'hourly'. Examples: 1 (day) if the request is for the forecast of today, 2 (days) if the request is for the weather this weekend, 6 (hours) if the request is for the weather periods like night, morning, afternoon and evening
        start_date:
          type: string
          description: >-
            This argument is mandatory and must always be provided no matter what! Provide the date on which the requested forecast starts. This date should be in the format YYYY-MM-DD. Always provide a date, so in case request is the forecast for today, provide today's date. When the forecast is for the night, do not use today's dat but always use the next day, unless the current time is still before 05:00:00
        start_time:
          type: string
          description: >-
            This argument is mandatory and must always be provided no matter what! Provide the time on which the requested forecast starts. This time should be in the format HH:MM:SS in 24 hour format (for example 17:00:00). Always provide a time. In case a full day is requested, use 00:00:00, in case the current hour is requested, use the start of the hour. Night starts at 00:00:00, morning starts at 06:00:00, afternoon starts at 12:00:00 and evening starts at 18:00:00
      required:
      - time_period_type
      - time_period_length
      - start_date
      - start_time
  function:
    type: script
    sequence:
    - service: script.llm_weather_forecast
      data:
        time_period_type: "{{time_period_type}}"
        start_date: "{{start_date}}"
        start_time: "{{start_time}}"
        time_period_length: "{{time_period_length}}"
```
