### ISSUE TITLE
Can't follow link from google search result to retreive page contents

### ISSUE THREAD

**Issue by jsgarvin** [jekalmin/extended_openai_conversation#288]
I have the following in the functions section for an agent to search for store hours.
```
- spec:
    name: search_google
    description: Search Google using the Custom Search API.
    parameters:
      type: object
      properties:
        query:
          type: string
          description: The search query.
      required:
      - query
  function:
    type: composite
    sequence:
    - type: rest
      resource_template: "https://customsearch.googleapis.com/customsearch/v1?key=[REMOVED]&cx=[REMOVED]&q={{ query }}&num=1"
      value_template: >-
        {% if value_json['items'] | length > 0 %}
        {{ value_json['items'][0]['link'] }}
        {% else %}
        No results found,
        {% endif %}
      response_variable: store_link
    - type: scrape
      resource_template: "{{ store_link }}"
      value_template: "{{ body }}"
      sensor:
      - name: body
        select: "body"
```
This results in the following error in the logs: `ERROR (MainThread) [homeassistant.components.automation.business_hours_query] Business Hours Query : Error executing script. Unexpected error for call_service at pos 2: ScrapeCoordinator.__init__() missing 1 required positional argument: 'update_interval'`

If I try to do a `rest` call instead of `scrape`...
```
- type: rest
      resource_template: "{{ store_link }}"
```
Then the Voice PE spins for a long time and eventually the logs say: `ERROR (MainThread) [homeassistant.components.rest.data] Timeout while fetching data: https://www.[THE COMPANY].com/store/[THE STORE PAGE]`

However, that's the correct URL and if I go there in my browser, it opens just fine.
