### ISSUE TITLE
RAG system integration

### ISSUE THREAD

**Issue by hugojm** [jekalmin/extended_openai_conversation#317]
I was considering creating my own knowledge base and using it as context (RAG), allowing the LLM to query it and learn about my life, appointments, and more.

**Comment by jekalmin** [comment]
Thanks for a new feature request.
I also want to dicuss the way it should provide.
Last time I [tried](https://github.com/jekalmin/extended_openai_conversation/pull/6), vector database and embeddings are so coupled that becomes hard for users to customize (some users are okay with cloud vector databases like supabase or pinecone, some are not).

What I'm trying now is using n8n for vector database and embeddings like below.
Please share thoughts.

## What I'm trying
### n8n
- Store data into a vector database 
- Create an API that retrievesdata from a vector database 

<img width="1810" height="474" alt="Image" src="https://github.com/user-attachments/assets/9a7c3c37-d3f3-4ef0-848e-e78f868b82d8" />

### Function

```yaml
- spec:
    name: search_calendar_schedules
    description: Use this function to search calendar schedules.
    parameters:
      type: object
      properties:
        query:
          type: string
          description: The query.
  function:
    type: rest
    method: POST
    headers:
      Content-Type: application/json
    resource: http://homeassistant:5678/webhook/c9ab3k20-54d1-423d-8032-b37c3a24c78e
    payload_template: >-
      {"text": "{{query}}"}
```

## Pros / Cons

- Pros
  - Users are able to choose vector databases and embeddings according to their taste
- Cons
  - Users have to setup n8n.

**Comment by jekalmin** [comment]
Here's what I have done so far.
I'm leaving this for anyone who is interested in RAG using Google Calendar.

## What it does
- Synchronize Google Calendar events with Qdrant vector database.
- Expose API endpoint from n8n which queries via similarity search.
- Add a function which calls API above.

## How to setup

### 1. Setup Qdrant (vector database)
1-1. Install [Qdrant](https://github.com/qdrant/qdrant)
1-2. From dashboard, create a collection (I named it `calendar`)
1-3. Add an index for `metadata.id` field (it will be used to delete an event)

<img width="1634" height="411" alt="Image" src="https://github.com/user-attachments/assets/9b933bb0-bff8-400e-81e2-f6eedf8e2aa5" />

### 2. Setup n8n
2-1. Install [n8n](https://github.com/n8n-io/n8n)
2-2. Create a workflow and import [n8n-workflow.json](https://github.com/user-attachments/files/24383523/n8n-workflow.json) via "Import from file..."
2-3. Setup API Keys, qdrant hosts, etc...

<img width="1107" height="514" alt="Image" src="https://github.com/user-attachments/assets/98675134-2d85-4631-a602-e0282e0bb0db" />

### 3. Add a Function in Extended OpenAI Conversation
3-1. Copy and paste below function, and replace `YOUR_N8N_HOST` to your n8n.
```yaml
- spec:
    name: search_calendar_events
    description: Search calendar events. Use this tool whenever user asks when or what time.
    parameters:
      type: object
      properties:
        query:
          type: string
          description: Raw user input text.
        limit:
          type: integer
          description: The number of result.
          minimum: 3
          maximum: 5
        time:
          type: string
          description: Specific time like "2025", "August", or etc.
      required:
        - query
        - limit
  function:
    type: rest
    method: POST
    headers:
      Content-Type: application/json
    resource: http://{{YOUR_N8N_HOST}}/webhook/e724f4d3-369f-4c4d-be19-acb7be42dc5b # replace {{YOUR_N8N_HOST}}
    payload_template: >-
      {"text": "{{time}} {{query}}, limit: {{limit}}"}
```

### 4. Ask about calendar events

<img width="410" height="462" alt="Image" src="https://github.com/user-attachments/assets/6c8b9eac-ad72-48f1-ba09-60fefa2d26e3" />
