### ISSUE TITLE
Function for local weather

### ISSUE THREAD

**Issue by rlust** [jekalmin/extended_openai_conversation#37]
What would the function look like to tell me my local weather from HA?

**Comment by jekalmin** [comment]
There are several ways to get it work, but the easist way might be following:

- add a "get_attributes" function
    ```yaml
    - spec:
        name: get_attributes
        description: Get attributes of any home assistant entity
        parameters:
          type: object
          properties:
            entity_id:
              type: string
              description: entity_id
          required:
          - entity_id
      function:
        type: template
        value_template: "{{states[entity_id]}}"
    ```
- expose your `weather.xxxxxx` entity.

**Reference**

- https://community.home-assistant.io/t/custom-component-extended-openai-conversation-lets-control-entities-via-chatgpt/636500/6

**Comment by jekalmin** [comment]
Before [this](https://github.com/jekalmin/extended_openai_conversation/issues/37#issuecomment-1833054261), I exposed entities of weather, humidity, temperature separately for current weather and registered a function for forecasts like below.

```yaml
- spec:
    name: get_weather_forecasts
    description: Get the weather forecasts between two dates.
    parameters:
      type: object
      properties:
        start:
          type: string
          description: The start date.
        end:
          type: string
          description: The end date.
      required:
      - start
      - end
  function:
    type: template
    value_template: >
      {% set data = states['weather.naver_weather'].attributes['forecast'] | selectattr('datetime', '>=', strptime(start, "%Y-%m-%d")) | selectattr('datetime', '<=', strptime(end + " 23:59:59", "%Y-%m-%d %H:%M:%S")) | list %}
      ```csv
      datetime,templow,temperature,condition,condition_am,condition_pm,rain_rate_am,rain_rate_pm
      {% for forecast in data -%}
      {{ forecast['datetime'] }},{{ forecast['templow'] }},{{ forecast['temperature'] }},{{ forecast['condition'] }},{{ forecast['condition_am'] }},{{ forecast['condition_pm'] }},{{ forecast['rain_rate_am'] }},{{ forecast['rain_rate_pm'] }}
      {% endfor -%}
      ```
```

**Comment by jekalmin** [comment]
Feel free to reopen the issue.

**Comment by dancwilliams** [comment]
[This](https://github.com/jekalmin/extended_openai_conversation/issues/37#issuecomment-1833054261) works great for me!  I can ask for the forecast today, tomorrow, etc and it works very well.

**Comment by momoz** [comment]
thanks the max tokens to 200 is what fixed it for me too.

**Comment by thematrixdev** [comment]
I am using AccuWeather.
![image](https://github.com/user-attachments/assets/f0764303-98f8-43ba-89f3-74fc65046c62)

Do you mean putting exactly these code onto the integration would make the attributes readable?
(And also all the attributes of the exposed entities?)
```
- spec:
    name: get_attributes
    description: Get attributes of any home assistant entity
    parameters:
      type: object
      properties:
        entity_id:
          type: string
          description: entity_id
      required:
      - entity_id
  function:
    type: template
    value_template: "{{states[entity_id]}}"
```

`Assist` cannot provide me the `temperature`.

And I see this warning after pasing the code:
![image](https://github.com/user-attachments/assets/a90cc688-5747-4abc-b594-24be67bcf6e4)

Thanks.
