### ISSUE TITLE
Integrating ytube_music_player

### ISSUE THREAD

**Issue by Zelaf** [jekalmin/extended_openai_conversation#38]
I'm trying to add some specs for full ytube_music_player integration.

Currently I'm trying to have it play from a list of playlist. I've added this in my prompt:
```
YouTube Music playlists:
```csv
playlist_id,playlist_name
*playlistid*,My Mix 1
*playlistid*,My Mix 2
*playlistid*,My Mix 3
*playlistid*,My Mix 4
*playlistid*,My Mix 5
*playlistid*,My Mix 6
*playlistid*,My Mix 7
*playlistid*,Chill Mix 1
*playlistid*,Chill Mix 2
*playlistid*,Chill Mix 3
*playlistid*,Energy Mix 1
*playlistid*,Energy Mix 2
*playlistid*,Energy Mix 3
```

And then this is what I'm trying for the spec:
```
- spec:
    name: play_music_playlist
    description: Use this function to play music from a playlist.
    parameters:
      type: object
      properties:
        playlist_id:
          type: string
          description: The ID of the playlist
      required:
      - playlist_id
  function:
    type: composite
    sequence:
    - type: script
      sequence:
      - service: media_player.play_media
        data:
          entity_id: media_player.youtube_music
          media_content_id: {{playlist_id}}
          media_content_type: playlist
          announce: true
```
However I'm getting
```
Sorry, I had a problem talking to OpenAI: [] is too short - 'functions'
```

I'm planning to add a function to each ytube_music_player function to have full control of it. Including picking a media player. Is there a way in the spec config to choose an already exposed media player?

**Comment by jekalmin** [comment]
> Sorry, I had a problem talking to OpenAI: [] is too short - 'functions'

I will change an error message and not even call API if failed to load yaml functions.

> Is there a way to specify so that it doesn't mix them up?

Please correct me if I'm wrong.
What you are trying to do is that you want gpt to look for playlists from prompt first, and search for playlists if it's not present in prompt.

As far as I know, you can try to tell gpt to do so by modifying prompt or description or name of functions.
Achieving this with general prompt is ideal, but specifically tell gpt about your case is totally fine like below (I haven't tested). 
`Do not search music for playlists if provided`

**Comment by Zelaf** [comment]
> As far as I know, you can try to tell gpt to do so by modifying prompt or description or name of functions.
> Achieving this with general prompt is ideal, but specifically tell gpt about your case is totally fine like below (I haven't tested).
> `Do not search music for playlists if provided`

That's smart, I'll test that!

I'm also thinking if it's possible to make "if"-type statements for a spec. If ytube_music_player already has a chosen media player or is playing media already to have it either skip choosing a media player or switch media player. Perhaps that can be put in the specs description too.

**Comment by jekalmin** [comment]
Oh, I haven't thought about it.
Could you give me an example of spec that you want to achieve?

Can't you achieve it by putting either choose or skip media player in prompt?

**Comment by Zelaf** [comment]
Perhaps like the search_music spec I could do something in the template section? Since the ytube_music_player device shows which device is currently playing, it could perhaps base of off that? 

So if the device is selected on the ytube_media_player property `remote_player_id: media_player.bedroom_display` don't initiate choose_player, else initiate choose.player.

**Comment by jekalmin** [comment]
> Edit: Also here's the current error I'm trying to fix, not sure if my way to do it is possible;
> `Sorry, I had a problem talking to OpenAI: Invalid schema for function 'music_choose_player': {'playback_device': None} is not of type 'string'`

In `required` field, I think it should be changed from `- playback_device:` to `- playback_device` like below.

```yaml
- spec:
    name: music_choose_player
    description: This function will choose the player to play back media to. Can also be used to switch current playback device.
    parameters:
      type: object
      properties:
        playback_device:
          type: string
          description: The speaker to play music on. Use entity ID of a speaker.
      required:
        - playback_device
  function:
    type: composite
    sequence:
      - type: script
        sequence:
          - service: media_player.select_source
            data:
              source: "{{playback_device}}"
              entity_id: media_player.youtube_music
```



> Perhaps like the search_music spec I could do something in the template section? Since the ytube_music_player device shows which device is currently playing, it could perhaps base of off that?

It seems that you want a feature like [if-then](https://www.home-assistant.io/docs/scripts/#if-then) in script function.

The "script" type function is designed to be same as [script](https://www.home-assistant.io/integrations/script/) integration in Home Assistant, but it currently has a bug when using [if-then](https://www.home-assistant.io/docs/scripts/#if-then) statement. I'm working on it, and it will probably be fixed in the next release.

However, you can achieve `if-then` clause by creating a separate script.

### Currently not working (will be fixed in the next release)
**Functions**
```yaml
- spec:
    ...
  function:
    type: script
    sequence:
      - if:
          - condition: state
            entity_id: ...
            state: "..."
        then:
          - service: media_player.select_source
            data: ...
```

### Workaround
**Functions**
```yaml
- spec:
    ...
  function:
    type: script
    sequence:
      - service: script.youtube_music_select_source
```

**script.youtube_music_select_source**
```yaml
alias: youtube_music_select_source
sequence:
  - if:
      - condition: state
        entity_id: ...
        state: "..."
    then:
      - service: media_player.select_source
        data: ...
mode: single

```
