### ISSUE TITLE
No logs?  Can't easily debug max token length exceeded error.

### ISSUE THREAD

**Issue by that1guy** [jekalmin/extended_openai_conversation#49]
Where do I look to find logs?

I have enabled logging in my configuration.yaml file [as documented here](https://github.com/jekalmin/extended_openai_conversation/tree/main?tab=readme-ov-file#logging), but i don't see any logs in HA's Setting -> System -> Logs .  

I am intermittently receiving the following error, and it's hard to debug without logs.

```
Sorry, I had a problem talking to OpenAI: This model's maximum context length is 4097 tokens. However, you requested 4202 tokens (3772 in the messages, 131 in the functions, and 299 in the completion). Please reduce the length of the messages, functions, or completion.
```

Amazing integration!

**Comment by saya6k** [comment]
Isn't it stored in `/config/home-assistant.log`?

**Comment by jekalmin** [comment]
Thanks for reporting an issue.

Currently, if known error occurs, the error message is responded to Assist without logging.
If unknown error occurs, the error message is logged and the response message is "Unexpected error during intent recognition."

In the next release (`0.0.9`), I am trying to log as much as possible. (https://github.com/jekalmin/extended_openai_conversation/pull/41)

I will also add logging of OpenAI API call in the next release.

**Comment by that1guy** [comment]
> @that1guy Have you checked `/config/home-assistant.log`?

Yes, checked.  Nothing of value in here.

**Comment by that1guy** [comment]
> Thanks for reporting an issue.
> 
> Currently, if known error occurs, the error message is responded to Assist without logging. If unknown error occurs, the error message is logged and the response message is "Unexpected error during intent recognition."
> 
> In the next release (`0.0.9`), I am trying to log as much as possible. (#41)
> 
> I will also add logging of OpenAI API call in the next release.

Excellent.  Great new @jekalmin

**Comment by jekalmin** [comment]
Fixed in [0.0.9-beta3](https://github.com/jekalmin/extended_openai_conversation/releases/tag/0.0.9-beta3)

**Comment by jekalmin** [comment]
Released in `0.0.9`.

**Comment by stefanbode** [comment]
Am I right this is the same issue? Asking for lights that are ON. Looks like I have to many lights. Using turbo-1106 version and latest 0.0.10 from yesterday. I assume about 30 lights get reported. any help welcome.

Something went wrong: failed to parse arguments `{"list":[{"domain":"light","service":"turn_off","service_data":{"entity_id":"light.vorratskellerlicht"}},{"domain":"light","service":"turn_off","service_data":{"entity_id":"light.ankleidezimmer_licht"}},{"domain":"light","service":"turn_off","service_data":{"entity_id":"light.wohnzimmer_licht"}},{"domain":"light","service":"turn_off","service_data":{"entity_id":"light.schlafzimmer_dimmer"}},{"domain":"light","service":"turn_off","service_data":{"entity_id":"light.kueche_licht_herd"}},{"domain":"light","service":"turn_off","service_data":{"entity_id":"light`. Increase maximum token to avoid the issue.

**Comment by stefanbode** [comment]
I changed to 3.5-16k model and now it runs fine. Anyhow I want to start a discussion if we are able to change the json to make it more token effective. Repeating "light", switch-on and all of these just increases the json. If we organize light on level one, switch state on level 2 and the just iterate on the items this is much smaller. For sure these needs changes on the loops running through the items. I would assume don't change the existing and just make a conversion of the json would me most effective. Is this possible with ChatGPT or do we have to stay with the formatting and accept the amounts of token.

**Comment by jekalmin** [comment]
> Am I right this is the same issue?

Yes. Since it is fixed, it resulted in the error message you wrote.



> Anyhow I want to start a discussion if we are able to change the json to make it more token effective

Can you try changing `entity_id` of `service_data` from `string` to `list` like below?

**Functions**
```yaml
- spec:
    name: execute_services
    description: Execute service of devices in Home Assistant.
    parameters:
      type: object
      properties:
        list:
          type: array
          items:
            type: object
            properties:
              domain:
                type: string
                description: The domain of the service.
              service:
                type: string
                description: The service to be called
              service_data:
                type: object
                description: The service data object to indicate what to control.
                properties:
                  entity_id:
                    type: array
                    items:
                      type: string
                      description: The entity_id retrieved from available devices. It must start with domain, followed by dot character.
                required:
                - entity_id
            required:
            - domain
            - service
            - service_data
  function:
    type: native
    name: execute_service
```

**Response**
```json
  {
    "finish_reason": "function_call",
    "index": 0,
    "message": {
      "content": null,
      "function_call": {
        "arguments": "{\"list\":[{\"domain\":\"switch\",\"service\":\"turn_on\",\"service_data\":{\"entity_id\":[\"switch.bedroom_left\",\"switch.bedroom_center\",\"switch.livingroom_l2\",\"switch.officeroom_top\"]}}]}",
        "name": "execute_services"
      },
      "role": "assistant"
    }
  }
```

**Comment by stefanbode** [comment]
Does this clear message he you to understand? Used 3.5-turbo


Sorry, I had a problem talking to OpenAI: This model's maximum context length is 4097 tokens. However, you requested 4169 tokens (3959 in the messages, 60 in the functions, and 150 in the completion). Please reduce the length of the messages, functions, or completion.

Doing the same request with the gpt-3.5- turbo-1106 does. Or report an error and seems to execute the command in the right way

**Comment by jekalmin** [comment]
It seems you have exposed too many entities, so it exceeds [limit](https://platform.openai.com/docs/models/gpt-3-5) of context windows.
`gpt-3.5-turbo-1106` model supports up to 16k tokens while `gpt-3.5-turbo` supports 4k.
However, it's better to lower the size of context since it costs depending on the size.

Try not to expose all entities, but to expose entities that are necessary.

**Comment by stefanbode** [comment]
Thanks. I know about the costs. Reduced from 190 to 140 entities. Maybe in the future it may help just to call the items in the domain and not all of them. But this require most likely two calls. One to understand what to filter and the the second call with all the objects relevant. For sure a very interesting space to work on. Anyhow the array is already an improvement.

**Comment by jekalmin** [comment]
@stefanbode 
Just released area capability in [1.0.1](https://github.com/jekalmin/extended_openai_conversation/releases/tag/1.0.1).
It might help reducing token consumption for multiple devices.

See https://github.com/jekalmin/extended_openai_conversation/tree/main/examples/function/area

**Comment by jekalmin** [comment]
Closing the issue.
Feel free to reopen it.

**Comment by FutureProofHomes** [comment]
Opening this back up for further instruction.  I've enabled logging per the documentation but I still can't see logs when I go to Setting -> System -> Logs.  I do however see logs when I tail `config/home-assistant.log`, but wow do I see this custom components info level logs pretty printed in the Home Assistant UI?

My configuration.yaml:
```
# Log the interactions between Home Assistant and custom chatGPT integration
logger:
  logs:
    custom_components.extended_openai_conversation: info
```
