### ISSUE TITLE
Thinks lights are only/on off (but still changes color?)

### ISSUE THREAD

**Issue by AsafMah** [jekalmin/extended_openai_conversation#52]
When trying to change the color of a light, it says to me that it can't change the color, only turn it on and off.
And then it changes the color anyway.

When asking what color is the light, it says it doesn't have this information.

Could it be a bug with how light entities are presented to the AI?

**Comment by jekalmin** [comment]
Since the color of the light should be retrieved from attributes, you have to add a function below to let gpt know the attributes of the entity.

```yaml
- spec:
    name: get_attributes
    description: Get attributes of any home assistant entity
    parameters:
      type: object
      properties:
        entity_id:
          type: string
          description: entity_id
      required:
      - entity_id
  function:
    type: template
    value_template: "{{states[entity_id]}}"
```

By default, only the state of entities are exposed.
