### ISSUE TITLE
The weather template has the temperature hard-coded as "25"

### ISSUE THREAD

**Issue by mr-biz** [jekalmin/extended_openai_conversation#68]
Hello, and Happy New Year!

First of all, thank you for this incredibly useful project.  

I noticed that the weather template has the temperature hard-coded as "25".

I tried adding in the temperature to the template myself but that did not work (Please see below). 

`- spec:
   ...
        temperature:
          type: string
          description: The temperature at the location
 ...
  function:
    type: template
    value_template: The temperature in {{ location }} is {{ temperature }} {{unit}}`

**Comment by jekalmin** [comment]
Happy New Year!

This was an example of [function calling](https://platform.openai.com/docs/guides/function-calling/common-use-cases) on OpenAI documentation.

Since OpenAI doesn't know real-time data like weather, the way to let it know is via function calling.
There are multiple ways to achieve this.

#### 1. Use temperature sensor in function
If you have temperature sensor, you can use it in a template.

```yaml
- spec:
    name: get_current_weather
    description: Get the current weather in a given location
    parameters:
      type: object
      properties:
        location:
          type: string
          description: The city and state, e.g. San Francisco, CA
        unit:
          type: string
          enum:
          - celcius
          - farenheit
      required:
      - location
  function:
    type: template
    value_template: The temperature in {{ location }} is {{ states("sensor.your_weather_temperature" )}} {{unit}}
```

#### 2. Expose temperature sensor
If you expose entities, the states of entities are injected into context(or system prompt).
So you don't have to add any functions. Just expose weather related sensors (the name of entities matters).

#### 3. Use attributes of `weather` entity
If you have a `weather.xxxxxx` entity, expose `weather.xxxxxx` entity and add `get_attributes` function below.

```yaml
- spec:
    name: get_attributes
    description: Get attributes of any home assistant entity
    parameters:
      type: object
      properties:
        entity_id:
          type: string
          description: entity_id
      required:
      - entity_id
  function:
    type: template
    value_template: "{{states[entity_id]}}"
```

By exposing `weather` entity, LLM notices that what entity_id of weather is and passes it to `get_attributes` function to retrieve details.

I'm using the last method because `get_attributes` function can be used not only for weather, but also for any entities.
