### ISSUE TITLE
entity_id should not be required for `execute_service`

### ISSUE THREAD

**Issue by MindFreeze** [jekalmin/extended_openai_conversation#86]
[Here](https://github.com/jekalmin/extended_openai_conversation/blob/d85230b51d778ebf2b5b5f9ea7fcdd1100e24cdd/custom_components/extended_openai_conversation/helpers.py#L240) an error is thrown if no entity is given. However most services can be called with only `area_id`. In fact having `area_id` is pointless if `entity_id` is required.
I tried tweaking the area_id parameter like this and ChatGPT tries to use correctly but gets the exception:
```yaml
area_id:
  type: string
  description: The id retrieved from areas. 
    You can specify only area_id without entity_id 
    to act on all entities in that area
```
